POST http://localhost:3000/user/sign-up
Content-Type: application/json

{
    "firstname":"khaled", 
    "lastname": "hegazy",
    "email":  "khaled.hegazy1842001@gmail.com",
    "password": "123m456789",
    "username": "KhaledHegazy"
}

###

POST http://localhost:3000/user/sign-in 
Content-Type: application/json

{
    "username":"MahmoudShakour",
    "password":"123m456789"
}


###

GET http://localhost:3000/user/MahmoudShakour 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4Njc3YzAwMjI0ZDgwNDQzNmQ5ZDkiLCJmaXJzdG5hbWUiOiJtYWhtb3VkIiwibGFzdG5hbWUiOiJhaG1lZCIsImVtYWlsIjoibWFobW91ZC5hbGkxODQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJExudmVqekI0NWFnQ1pMRDFFTHdIbC5QcDRyOG5LcWJjc0wvQXJueDBXUjV4UGwyd0twcUZ1IiwidXNlcm5hbWUiOiJNYWhtb3VkU2hha291ciIsInJvbGUiOiJhZG1pbiIsIl9fdiI6MCwiaWF0IjoxNjg0NTkyNjExfQ.Yyfk7_49S8k3ewmBy1iAMX8hT3FJGhXQkw1JYYLmQSg
###

PUT http://localhost:3000/user/KhadHegazy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4Njc3YzAwMjI0ZDgwNDQzNmQ5ZDkiLCJmaXJzdG5hbWUiOiJtYWhtb3VkIiwibGFzdG5hbWUiOiJhaG1lZCIsImVtYWlsIjoibWFobW91ZC5hbGkxODQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJExudmVqekI0NWFnQ1pMRDFFTHdIbC5QcDRyOG5LcWJjc0wvQXJueDBXUjV4UGwyd0twcUZ1IiwidXNlcm5hbWUiOiJNYWhtb3VkU2hha291ciIsInJvbGUiOiJhZG1pbiIsIl9fdiI6MCwiaWF0IjoxNjg0NTkyNjExfQ.Yyfk7_49S8k3ewmBy1iAMX8hT3FJGhXQkw1JYYLmQSgContent-Type: application/json

{
    "firstname":"mahmoud",
    "lastname":"ahmed"
}

###

POST http://localhost:3000/blog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4Njc3YzAwMjI0ZDgwNDQzNmQ5ZDkiLCJmaXJzdG5hbWUiOiJtYWhtb3VkIiwibGFzdG5hbWUiOiJhaG1lZCIsImVtYWlsIjoibWFobW91ZC5hbGkxODQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJExudmVqekI0NWFnQ1pMRDFFTHdIbC5QcDRyOG5LcWJjc0wvQXJueDBXUjV4UGwyd0twcUZ1IiwidXNlcm5hbWUiOiJNYWhtb3VkU2hha291ciIsInJvbGUiOiJhZG1pbiIsIl9fdiI6MCwiaWF0IjoxNjg0NTkyNzU3fQ.Q1NAxBzRfuzn1_oqbAqMnmW8UcjdRnvORK9pfEEP87c
Content-Type: application/json

{
    "content": "this is the content of another the blog",
    "title": "blog title",
    "status": "public"
}

###

GET http://localhost:3000/blog/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4Njc3YzAwMjI0ZDgwNDQzNmQ5ZDkiLCJmaXJzdG5hbWUiOiJtYWhtb3VkIiwibGFzdG5hbWUiOiJhaG1lZCIsImVtYWlsIjoibWFobW91ZC5hbGkxODQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJExudmVqekI0NWFnQ1pMRDFFTHdIbC5QcDRyOG5LcWJjc0wvQXJueDBXUjV4UGwyd0twcUZ1IiwidXNlcm5hbWUiOiJNYWhtb3VkU2hha291ciIsInJvbGUiOiJhZG1pbiIsIl9fdiI6MCwiaWF0IjoxNjg0NTkyNzU3fQ.Q1NAxBzRfuzn1_oqbAqMnmW8UcjdRnvORK9pfEEP87c


###

PUT http://localhost:3000/blog/6468e8280a7582dfdc326771
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4Njc3YzAwMjI0ZDgwNDQzNmQ5ZDkiLCJmaXJzdG5hbWUiOiJtYWhtb3VkIiwibGFzdG5hbWUiOiJhaG1lZCIsImVtYWlsIjoibWFobW91ZC5hbGkxODQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJExudmVqekI0NWFnQ1pMRDFFTHdIbC5QcDRyOG5LcWJjc0wvQXJueDBXUjV4UGwyd0twcUZ1IiwidXNlcm5hbWUiOiJNYWhtb3VkU2hha291ciIsInJvbGUiOiJhZG1pbiIsIl9fdiI6MCwiaWF0IjoxNjg0NTkyNzU3fQ.Q1NAxBzRfuzn1_oqbAqMnmW8UcjdRnvORK9pfEEP87c
Content-Type: application/json

{
    "content": "this is the content of the blog",
    "title": "blog title2",
    "status": "private"
}


// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY4Njc3YzAwMjI0ZDgwNDQzNmQ5ZDkiLCJmaXJzdG5hbWUiOiJtYWhtb3VkIiwibGFzdG5hbWUiOiJhaG1lZCIsImVtYWlsIjoibWFobW91ZC5hbGkxODQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJExudmVqekI0NWFnQ1pMRDFFTHdIbC5QcDRyOG5LcWJjc0wvQXJueDBXUjV4UGwyd0twcUZ1IiwidXNlcm5hbWUiOiJNYWhtb3VkU2hha291ciIsInJvbGUiOiJhZG1pbiIsIl9fdiI6MCwiaWF0IjoxNjg0NTkyNzU3fQ.Q1NAxBzRfuzn1_oqbAqMnmW8UcjdRnvORK9pfEEP87c
